FROM python:3.12

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir streamlit requests pandas plotly

CMD ["streamlit", "run", "frontend_streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]