FROM python:3.12

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir streamlit requests pandas plotly

CMD ["sh", "-c", "streamlit run frontend/frontend_streamlit.py --server.port $PORT --server.address 0.0.0.0"]