services:
  - type: web
    name: estoque-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: estoque-db
          property: connectionString
      - key: SECRET_KEY
        value: 0f080d5a3440719d3c9bafbe820c50c3601f87340cf067bc8c82abd
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 1600

  - type: web
    name: estoque-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    autoDeploy: true

  - type: web
    name: n8n-stoque
    env: docker
    plan: free
    image:
      url: n8nio/n8n
    autoDeploy: true
    envVars:
      - key: N8N_PORT
        value: 5678
    mounts:
      - type: volume
        source: n8n_data
        target: /home/node/.n8n

databases:
  - name: estoque-db
    databaseName: controle_estoque
    user: estoque_user
    plan: free

volumes:
  - name: n8n_data